const roomData = [
    { name: 'Pères', data: 'dad', title: 'les pères', info: 'Au cœur de cet espace dédié, nous célébrons les pères remarquables. Leur amour résolu et leurs sacrifices silencieux transforment l\'ordinaire en exceptionnel. Architectes de courage, gardiens de rêves, ils sont les héros discrets qui éclairent notre parcours. Dans cette salle, chaque père brille d\'une lueur indomptable.' },
    { name: 'Mères', data: 'mum', title: 'les mères', info: 'Dans cette enclave dédiée, nous honorons les mères extraordinaires. Leur amour inconditionnel et leur dévouement transforment l\'ordinaire en extraordinaire. Gardiennes de souvenirs, architectes de vies, elles sont les héroïnes discrètes qui guident notre chemin. Dans cette salle, chaque mère rayonne d\'une lumière éternelle.' },
    { name: 'Soeurs', data: 'sister', title: 'les soeurs', info: 'En ce lieu d\'admiration, nous honorons les sœurs remarquables. Leur amour inconditionnel et leur soutien indéfectible transforment l\'ordinaire en exceptionnel. Architectes de douceur, compagnes de joie, elles sont les héroïnes discrètes qui éclairent notre existence. Dans cette salle, chaque sœur brille comme une étoile, témoignage d\'un lien éternel.' },
    { name: 'Frères', data: 'brother', title: 'les frères', info: 'Au sein de cet espace dédié, nous célébrons les frères exceptionnels. Leur amitié sincère et leur dévouement transforment l\'ordinaire en extraordinaire. Architectes de complicité, compagnons de vie, ils sont les héros discrets qui partagent notre chemin. Dans cette salle, chaque frère brille comme une étoile, symbole d\'une connexion éternelle.' },    
    { name: 'Cousin.e.s', data: 'cousin', title: 'les cousines et cousins', info: 'En cet espace dédié, nous mettons en lumière les cousins et cousines admirables. Leurs liens chaleureux et leurs souvenirs partagés transforment l\'ordinaire en extraordinaire. Architectes de complicité, compagnons de jeux, ils sont les héros discrets qui enrichissent notre histoire. Dans cette salle, chaque lien fraternise avec une éclatante proximité.' },
    { name: 'Ami.e.s', data: 'friend', title: 'les ami.e.s', info: 'Au cœur de cette enclave, nous célébrons les amis exceptionnels. Leur amitié sincère et leurs moments partagés transforment l\'ordinaire en extraordinaire. Architectes de rires, compagnons de peines, ils sont les héros discrets qui colorent notre existence. Dans cette salle, chaque amitié brille d\'une lumière indéfectible.' },
    { name: 'Grand Parents', data: 'grandparent', title: 'les grands parents', info: 'Dans cet espace de reconnaissance, nous honorons les grands-parents admirés. Leur sagesse infinie et leur amour incommensurable transforment l\'ordinaire en exceptionnel. Gardiens de traditions, conteurs d\'histoires, ils sont les héros discrets qui éclairent notre passé. Dans cette salle, chaque grand-parent rayonne d\'une affection éternelle.' },
    { name: 'Amour', data: 'love', title: 'l\'amour', info: 'En ce lieu dédié, nous célébrons l\'amour inébranlable envers nos conjoints. Leurs sourires tendres et leurs étreintes chaleureuses transforment l\'ordinaire en un éternel enchantement. Architectes de complicité, partenaires de rêves, ils sont les héros discrets qui illuminent notre vie. Dans cette salle, chaque amour émane d\'une éternelle flamme.' },
    { name: 'Générosité', data: 'generosite', title: 'les personnes les plus généreuses', info: 'En cet espace dédié, nous mettons en lumière les âmes généreuses. Leurs actes désintéressés transforment l\'ordinaire en un festin de bienveillance. Architectes de compassion, bienfaiteurs silencieux, ils sont les héros discrets qui nourrissent notre humanité. Dans cette salle, chaque geste résonne comme une mélodie de bonté éternelle.' },
    { name: 'Gentillesse', data: 'gentillesse', title: 'les personnes les plus gentilles', info: 'Au cœur de cette enclave, nous célébrons les personnes d\'une gentillesse rayonnante. Leurs paroles douces et leurs gestes bienveillants transforment l\'ordinaire en une toile de délicatesse. Architectes de réconfort, artisans de sourires, ils sont les héros discrets qui illuminent notre quotidien. Dans cette salle, chaque acte rayonne d\'une lumière bienfaisante éternelle.' },
    // Ajoutez d'autres salles au besoin
  ];
  
  export default roomData;


  